### ISSUE TITLE
Lipid14distance.py AttributeError: 'Residue' object has no attribute 'center_of_mass' 

### ISSUE THREAD

**Issue by HeisenbergGuo** [bio-phys/cnt-lipid14-analysis#1]
Hi, 
Thanks for sharing this analysis code.

I'm new to MDanalysis, I tried the lipid14distance.py code running with Gromacs setup.
However, it stops and pops out "AttributeError: 'Residue' object has no attribute 'center_of_mass'"

To change Line 114 from
```
com_lip = res.center_of_mass()
```
to 
```
com_lip = res.atoms.center_of_mass()
```
seems do the trick.

The code seems originally served for an amber software analysis, I'm not sure it is caused by that I use a Gromacs input (tpr, xtc) or a Mdanalysis package version difference. 

Just comment it here.

**Comment by martinvoegele** [comment]
Thanks for pointing this out!
I changed it accordingly, so it should work with the new MDAnalysis version.

Concerning input from different software, you should just make sure that the residues are still named correctly (or otherwise adapt the selection in the script accordingly).
